// [resources.h] is generated by this file [resources.in]. Do not modify [resources.h] manually.
// This header file contains the path to the Data Folder, which is needed by the program
// This path is set by CMakeLists.txt at building time
#define _DATAFILESPATH_ "/Users/me/Project/CUniMolSys/Data"
