function(my_add_test name)
    file(GLOB sources *.cpp)
    enable_testing()
    include(GoogleTest)
    add_executable(${name} "${sources}")
    message("${CMAKE_CURRENT_LIST_DIR}")
    target_link_libraries(${name} PRIVATE gtest gtest_main cunimolsys)
    target_link_directories(${name} PRIVATE ../../lib)
    target_include_directories(${name} PRIVATE ../../include)
    gtest_discover_tests(${name})
endfunction()